{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "filestat.fullname" . }}
  labels:
    {{- include "filestat.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "filestat.fullname" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end -}}
