apiVersion: v1
kind: ConfigMap
metadata:
  name: filestat-main
  labels:
    {{- include "filestat.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.fileConfigs }}
  {{$key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
