apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-{{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.files }}
  {{ $key }}: |-
{{ $value | default "{}" | indent 4 }}
{{- end -}}
