{
 "title": "Logging Centralized Logs->Fluentbit->Fluentd",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,20s,30s,40s,50s,1m,2m,10m"
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(kube_pod_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$nodename\"}, namespace) "
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(fluentd_input_status_num_records_total{job=\"fluentd\",nodename=~\"$nodename\",tag=~\".*$namespace.*\"},tag)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "#FB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{job=\"kubernetes-service-endpoints\",pod=~\".*fluentbit.*\" })",
       "legendFormat": "Active Fluent-bit"
      }
     ]
    },
    {
     "title": "# FD",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{job=\"kubernetes-service-endpoints\",pod=~\".*fluentd.*\"})",
       "legendFormat": "Active Fluent-bit"
      }
     ]
    },
    {
     "title": "#Log - FB In",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "abs( sum(rate(file_content_line_number{path=~\"/var/log/containers/.*\"}[$interval])) - on () sum(rate(fluentbit_input_records_total{job=\"fluentbit-fluent-bit\",name=~\"tail.*\"}[$interval])) )",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FB In - Out",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "abs(sum by(name) (rate(fluentbit_input_records_total{job=\"fluentbit-fluent-bit\",name=\"tail.0\" }[$interval])) - on () sum by()  (rate(fluentbit_output_proc_records_total{job=\"fluentbit-fluent-bit\",name=\"forward.0\"}[$interval])))",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "POD # Lines",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(file_content_line_number{path=~\"/var/log/containers/.*\"}[$interval]))",
       "legendFormat": "POD # Lines"
      }
     ]
    },
    {
     "title": "Fluentbit Out FWD",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_records_total{job=\"fluentbit-fluent-bit\",name=~\"forward.*\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Fluentd Output",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_records_total{job=\"fluentd\"}[$interval]))"
      }
     ]
    },
    {
     "title": "FB Dropped",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_output_dropped_records_total{job=\"fluentbit-fluent-bit\"})",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FB Retry",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_retried_records_total{job=\"fluentbit-fluent-bit\"}[$interval]))",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FB Retry Fail",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_output_retries_failed_total{job=\"fluentbit-fluent-bit\"})",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FB Out - FD In",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "abs( sum by (name) (rate(fluentbit_output_proc_records_total{job=\"fluentbit-fluent-bit\",name=\"forward.0\"}[$interval])) - on () sum(rate(fluentd_input_status_num_records_total{job=\"fluentd\"}[$interval])))",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FD In - FD  Out ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "abs( sum(rate(fluentd_input_status_num_records_total{job=\"fluentd\"}[$interval])) - on () sum(rate(fluentd_output_status_num_records_total{job=\"fluentd\"}[$interval])) )",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FD # error",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) )",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    },
    {
     "title": "FD slow flush",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_slow_flush_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) )",
       "legendFormat": "fluentbit_output_dropped_records_total"
      }
     ]
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": " Pod log lines vs Fluentbit  incoming records",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(file_content_line_number{path=~\"/var/log/containers/.*\"}[$interval]))",
     "legendFormat": "Pod # Line"
    },
    {
     "expr": "sum(rate(fluentbit_input_records_total{job=\"fluentbit-fluent-bit\",name=~\"tail.*\"}[$interval]))",
     "legendFormat": "Fluent Bit Input tail {{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Fluentbit  incoming records vs Fluentbit  outgoing records",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(fluentbit_input_records_total{job=\"fluentbit-fluent-bit\" }[$interval]))",
     "legendFormat": "Fluent Bit Input {{name}} {{instance}}"
    },
    {
     "expr": "sum by(name)  (rate(fluentbit_output_proc_records_total{job=\"fluentbit-fluent-bit\" }[$interval]))",
     "legendFormat": "Fluent Bit Output {{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Fluentbit output records vs Fluentd incoming records",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": " sum by (name) (rate(fluentbit_output_proc_records_total{job=\"fluentbit-fluent-bit\"}[$interval]))",
     "legendFormat": "Fluent Bit Output {{name}} "
    },
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{job=\"fluentd\" }[$interval]))",
     "legendFormat": "Fluentd Input  {{name}} "
    }
   ]
  },
  {
   "title": "Fluentd  incoming records vs Fluentd outgoing records",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{job=\"fluentd\"}[$interval]))",
     "legendFormat": "Fluentd Input "
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{job=\"fluentd\"}[$interval]))",
     "legendFormat": "Fluentd Output"
    }
   ]
  },
  { "title": "Ingestion Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": " Pod log lines ",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "\r\nlabel_replace(\r\n\tsum(rate(file_content_line_number{path=~\"/var/log/containers/.*\", path=~\".*$pod.*\"}[$interval]) ) by (path),\r\n\t\"podname\",\r\n\t\"$1\",\r\n\t\"path\",\r\n\t\"/var/log/containers/(.*)_(.*)_(.*).log\"\r\n)\r\n",
     "legendFormat": "Pod # Line {{podname}}"
    }
   ]
  },
  {
   "title": "Buffers size fluentbit",
   "type": "graph",
   "description": "Size of duffers in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(file_stat_size_bytes{job=\"filestat\",path=~\"/.*/.*/fluentbit-storage/flbstore/tail.0/.*\"}) by (nodename)",
     "legendFormat": "Fluent Bit buffer Tail: {{nodename}} "
    }
   ]
  },
  {
   "title": "Buffers size fluentd Azure Blob Storage",
   "type": "graph",
   "description": "Size of duffers in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(file_stat_size_bytes{job=\"filestat\",path=~\"/.*/.*/fluentd-buffers/azure_storage_append_blob/.*/.*\"}) by ( nodename)",
     "legendFormat": "Fluentd buffer Azure: {{nodename}}"
    }
   ]
  },
  {
   "title": "Logs pods size",
   "type": "graph",
   "description": "Size of /var/log/containers/ logs in bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\r\n\trate(file_stat_size_bytes{ path=~\"/var/log/containers/.*\",nodename=~\".*$nodename.*\",path=~\".*$namespace.*\",path=~\".*$pod.*\"}[$interval]),\r\n\t\"podname\",\r\n\t\"$1\",\r\n\t\"path\",\r\n\t\"/var/log/containers/(.*)_(.*)_(.*).log\"\r\n)",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "Buffers size fluentd Elasticsearch",
   "type": "graph",
   "description": "Size of duffers in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(file_stat_size_bytes{job=\"filestat\",path=~\"/.*/.*/fluentd-buffers/elasticsearch/.*/.*\"}) by ( nodename)",
     "legendFormat": "Fluentd buffer Elastic: {{nodename}}"
    }
   ]
  },
  {
   "title": "Fluentd  incoming records vs Fluentd outgoing records",
   "type": "graph",
   "description": "Total number of incoming records vs total number of outgoing records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (nodename,worker_id) (rate(fluentd_input_status_num_records_total{job=\"fluentd\"}[$interval]))",
     "legendFormat": "Fluentd Input {{nodename}} {{worker_id}}"
    },
    {
     "expr": "sum by (nodename,worker_id) (rate(fluentd_output_status_num_records_total{job=\"fluentd\"}[$interval]))",
     "legendFormat": "Fluentd Output {{nodename}} {{worker_id}}"
    }
   ]
  },
  {
   "title": "Fluent Bit details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluentbit_output_retried_records_total",
     "type": "graph",
     "description": "Number of retried records.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_retried_records_total{job=\"fluentbit-fluent-bit\"}[$interval])",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "fluentbit_output_retries_failed_total",
     "type": "graph",
     "description": "Number of abandoned batches because the maximum number of re-tries was reached.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_retries_failed_total{job=\"fluentbit-fluent-bit\"}[$interval])",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "fluentbit_output_retries_total",
     "type": "graph",
     "description": "Number of output retries.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_retries_total{job=\"fluentbit-fluent-bit\"}[$interval])",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "fluentbit_output_errors_total",
     "type": "graph",
     "description": "Number of output errors.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_errors_total{job=\"fluentbit-fluent-bit\"}[$interval])",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "fluentbit_output_dropped_records_total",
     "type": "graph",
     "description": "Number of dropped records.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_dropped_records_total{job=\"fluentbit-fluent-bit\"}[$interval])",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluentd Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluentd_input_status_num_records_total",
     "type": "graph",
     "description": "# The total number of incoming records",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\n\trate(fluentd_input_status_num_records_total{job=\"fluentd\", tag=~\".*$namespace.*\", tag=~\".*$pod.*\"}[$interval]),\r\n\t\"podname\",\r\n\t\"$1\",\r\n\t\"tag\",\r\n\t\"kube.var.log.containers.(.*)_(.*)_(.*).log\"\r\n)",
       "legendFormat": "{{nodename}}  {{worker_id}} {{podname}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_num_records_total ",
     "type": "graph",
     "description": "# The total number of outgoing records",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\n\trate(fluentd_output_status_num_records_total{job=~\"fluentd\", tag=~\".*$namespace.*\",  tag=~\".*$pod.*\"}[$interval]),\r\n\t\"podname\",\r\n\t\"$1\",\r\n\t\"tag\",\r\n\t\"kube.var.log.containers.(.*)_(.*)_(.*).log\"\r\n)",
       "legendFormat": "{{nodename}}  {{worker_id}} {{podname}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_retry_wait",
     "type": "graph",
     "description": "# maximum retry wait in last 1min",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_retry_wait{job=~\"fluentd\"}[$interval])",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_retry_count",
     "type": "graph",
     "description": "# retry count / sec",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_retry_count{job=~\"fluentd\"}[$interval])",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_total_bytes",
     "type": "graph",
     "description": "maximum buffer bytes in last 1min",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_total_bytes{job=~\"fluentd\"}[$interval])",
       "legendFormat": "{{nodename}}  {{type}} {{worker_id}}"
      }
     ]
    },
    {
     "title": "# maximum buffer length in last 1min",
     "type": "graph",
     "description": "# maximum buffer length in last 1min",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length{job=~\"fluentd\"}[$interval])",
       "legendFormat": "{{nodename}}  {{type}} {{worker_id}}"
      }
     ]
    },
    {
     "title": "fluentd_status_buffer_queue_length",
     "type": "graph",
     "description": "Current buffer queue length.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_status_buffer_queue_length{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_status_buffer_total_bytes",
     "type": "graph",
     "description": "Current total size of queued buffers.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_status_buffer_total_bytes{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": " {{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_total_bytes",
     "type": "graph",
     "description": "Current total size of stage and queue buffers.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_total_bytes{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_stage_byte_size",
     "type": "graph",
     "description": "Current total size of stage buffers.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_byte_size{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_queue_length",
     "type": "graph",
     "description": "Current length of queue buffers",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_stage_length",
     "type": "graph",
     "description": " Current length of stage buffers.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_length{job=\"fluentd\",nodename=~\"$nodename\"}) by (nodename, type)",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_buffer_available_space_ratio",
     "type": "graph",
     "description": "Ratio of available space in buffer.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "fluentd_output_status_buffer_available_space_ratio{job=\"fluentd\",nodename=~\"$nodename\"}",
       "legendFormat": "{{nodename}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_num_errors",
     "type": "graph",
     "description": "Current number of errors.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_num_errors{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_emit_count",
     "type": "graph",
     "description": "Current emit counts.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_emit_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_write_count",
     "type": "graph",
     "description": " Current write counts.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_write_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_rollback_count",
     "type": "graph",
     "description": "Current rollback counts.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_rollback_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_flush_time_count",
     "type": "graph",
     "description": "Total flush time.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_flush_time_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_output_status_slow_flush_count",
     "type": "graph",
     "description": "Current slow flush counts.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_output_status_slow_flush_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    },
    {
     "title": "fluentd_status_retry_count",
     "type": "graph",
     "description": "Current retry counts.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentd_status_retry_count{job=\"fluentd\",nodename=~\"$nodename\"}[$interval]) ",
       "legendFormat": "{{nodename}} {{worker_id}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{node=~\"$nodename\", namespace=~\"infra.*\", pod=~\"fluentbit.*|fluentd.*|filestat.*\" }) by (node, namespace, pod)",
       "legendFormat": "{{node}} : {{namespace}} : {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)  by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{node=~\"$nodename\", namespace=~\"infra.*\", pod=~\"fluentbit.*|fluentd.*|filestat.*\"}) by (node, namespace, pod)",
       "legendFormat": "{{node}} : {{namespace}} : {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}